import random

prefix_list = {
1: "One:Can only be fired once per day. Deals 10x Damage.",
2: "Normal:Appearance of a Common Gun.",
3: "Adorable:25% to distract Enemies with baby hallucinations",
4: "Gaudy:Highly refletice, which can be used to temporarily blind Enemies, giving them -3 of Attack Rolls.",
5: "Cheerful:Grants +1 to all Talk Checks while equipped.",
6: "Jumbled:Has the Accuracy and Damage, but the Range and bonuses of another.",
7: "Classy:Gun will only fire if the wielder has the pinky of their shooting hand out.",
8: "Economic:Enemies drop 2 gold per Hit and 5 gold per Crit.",
9: "Certain:Grants a +2 bonus during Badass attempts.",
10: "Humdrum:Enemies Hit experience ennui.",
11: "Lively:This gun has an AI that thinks it's alive. It can only any door once per day.",
12: "Bitter:Enemies get -1 to their Attack Rolls for each enemy killed by this gun in this encounter.",
13: "Sleepy:Enemies Hit are Slowed.",
14: "Deafening:Screams when fired, dealing 1 Damage to all adjacent targets.",
15: "Selfish:Deals 1d6 Damage to wielder when changing to another equipped gun.",
16: "Obtainable:Must be picked up using an Interact (17+) Check.  Deals 2x Damage.",
17: "Abrasive: Adds +1 Crit to Melee Attacks.",
18: "Smelly:Enemies Hit take 1d6 Radiation Damage.",
19: "Tart:Enemies react as if they have eaten something tart, getting -1 to their next Attack Roll.",
20: "Worried:Crits have a 50% chance to make a BR 8 or less Enemy flee.",
21: "Swift:Grants a free Melee Attack each turn.",
22: "Two:Creates a duplicate gun. Must be fired at the same time. 3x Damage.",
23: "Toothsome:Gets a Bite Attack each turn for 1d6 Damage to an adjacent target.",
24: "Light:Fires rays of light that deal +1d6 Incendiary Damage.",
25: "Boundless:Generates a Loot Pile when it hits an Enemy.",
26: "Incandescent:Shines brighter when being fired.",
27: "Elfin:Increases Movement by 1 square while firing.",
28: "Splendid:Deals 2x Damage to Badass-type Enemies.",
29: "Small:Can have 4th gun equipped as long as this gun is equipped.",
30: "Pumped:Lifts Enemies Hit a foot off the ground.",
31: "Horrible:Enemies killed by this gun explode.",
32: "Fresh:First Attack of an encounter deals 2x Damage.",
33: "Zesty:Enemies killed by this gun grant the wielder 1 Badass Token.",
34: "Utter:There is a secret password that activates 3x Damage for the next 2 turns.Wielder can gues once per encounter.",
35: "Far-Flung:Double the Range of any Thrown item while this gun is equipped.",
36: "Superb:Grants +1 to Mods on the gun.",
37: "Knotty:Ties an Enemy's shoes together, reducing their Movement by 1.",
38: "Wrathful:Deals 2x Damage to enemies that have Damaged the wielder.",
39: "Panoramoic:Fires in a 180 degree arc. Hits/Crits can each be applied to a different Enemy in Range.",
40: "Critical:Rolled Hits become Crits. Rolled Crits become misses.",
41: "Practical:Swapping to a different gun grants the wielder a badass token.",
42: "Strong:Grants +1 to all Interact Checks while rquipped.",
43: "Relevent:Will deliver cryptic information on a topic up to 3x per day.",
44: "Tense:30% chance to taze the Enemy, dealing 1d6 Shock Damage.",
45: "Stupendous:Double the Hits of this gun. Attacks deal 2d4 Damage to the wielder.",
46: "Suitable:Can disguise the wielder in a suit of any kind once per day.",
47: "Unwieldy:Twice the size of a normal gun. 2x Damage. Reloading takes 2 turns.",
48: "Woozy:Each time an Enemy is hit by this gun, 10% chance they pass out.",
49: "Grotesque:Gun looks horrific, possibly cursed. A counter increases every time it kills an Enemy.",
50: "Puny:Appearance of a miniature gun.",
51: "Tawdry:When Reloaded, becomes a grenade that deals 3d8 Damage.",
52: "Nutty:Insstantly kills any Enemy with a nut allergy.",
53: "Adhesive: Enemies Hit begin to stick to anything they come into contact with.",
54: "Exciting:50% chance for Explosive rounds.",
55: "Mixed:For each Hit/Crit, gather the next die for Damage, ie d6, d8, d10, d12, d20.",
56: "Aback:Enemies Hit in the front are spun backwards.",
57: "Labored:Adds +3 DMG Mod if standing still.",
58: "Questionable:Deals 2x Damage to Enemies that can question their existence.",
59: "Aberrant:Gains the stats of a random gun type.",
60: "Resolute:Cannot be fired on the first turn of an Encounter. Deals 2x Damage.",
61: "Far:Double the Range of this gun.",
62: "Mad:Enemies Hit have a 50% chance of being Taunted.",
63: "Grey:Deals 2x Damage. Enemies Hit drop 1 less Loot Pile and only drop Common items.",
64: "Damp:Creates puddles of water under Enemies Hit.",
65: "Actually:Can reroll Accuracy once per turn while firing this gun.",
66: "Jazzy:10% chance the non-Boss enemy let's go of any weapons and starts doing 'jazz hands'.",
67: "Frightening:Enemies within 2 squares are compelled to take Cover.",
68: "Shaky:Gun shakes uncontrollably: Enemies Hit also shake uncontrollably.",
69: "Scintillating:50% chance to Hit the chest or groin of Enemy.",
70: "Handsomely: Add Damage equal to your Talk modifier.",
71: "Hysterical:Enemies Hit burst out laughing, causing -1 to Attack Rolls.",
72: "Impolite:Randomly burps out a Loot Pile when fired.",
73: "Unable:Enemies Hit cannot take Mayhem Actions.",
74: "Towering:Wielder appears twice their size while gun is equipped.",
75: "Parallel:Rounds split into 2 parallel lines that can Hit Enemies in 2 adjacent squares.",
76: "Mundane:Grants +1 to all Sneak checks while equipped.",
77: "Breezy:Enemies targeted are struck by a gust of wind that pushes them 1 square backwards.",
78: "Disgusted:Deals +1d6 Corrosive Damage. Enemies killed die badly.",
79: "Imaginary:Appears as if you are not holding any gun. Makes fake firing noises when fired.",
80: "Knowing:Knows all. Can ask the gun a question once per day.",
81: "Joyous:Plays upbeat music when being fired.",
82: "Clever:Grants +1 to all Insight checks while equipped.",
83: "Abhorrent:Enemies cannot stay within 1 square while this gun is equipped.",
84: "Open:Once per turn, you may Reload this gun as a Free Action without generating Mayhem.",
85: "Several:Splits into 2 guns that are dual wielded.",
86: "Honorable:All rounds Hit Enemies in the front.",
87: "Synonymous:Grants Guild bonuses twice.",
88: "Madly:Enemies hit have a 50% chance of becoming Confused.",
89: "Obnoxious:Guaranteed Insight Check once per day at the cost of having to listen to the gun drone on and on and on.",
90: "Holistic:Damage is dealt to Shield, Armor, and Health.",
91: "Few:Max 1 Hit. Deal an additional 3 Damage for each unused Hit.",
92: "Legal:Enemies Hit are considered to be under a legally binding contract to drop 1 extra Loot Pile when they die.",
93: "Abiding:Grants +1 to all Search Checks while equipped.",
94: "Unfair: An Extra Attack with this gun does not generate Mayhem.",
95: "Tender:Converts 10% of Damage dealth into Health for an adjacent ally.",
96: "Same:Enemies Hit will take an equal amount of Damage from the gun for each Attack.",
97: "Overconfident:If Accuracy Roll is 10 or less, all Hits are Crits.",
98: "Eatable:Can consume the gun when Reloading to gain 2d4 Health.",
99: "Thirsty:Converts 10% of Damage dealt into Health.",
100: "Imminent: Enemies Hit take increasing Damage with each turn. Damage starts at 1 and increased by 1 with each Hit/turn."
    }



def prefix_gen():
    prefix_choice = prefix_list[(random.randint(1,100))]
    #split it into prefix & effect
    prefix, prefix_effect = prefix_choice.split(":",1)
    return prefix, prefix_effect
