import random

class_relics = {
1: 'Assassin',
2: 'Berserker',
3: 'Commando',
4: 'Gunzerker',
5: 'Hunter',
6: 'Mecromancer',
7: 'Psycho',
8: 'Siren',
9: 'Soldier',
10: 'Any'
    }



relics = {
1: 'Vitality: +20 Max Health.  Class Bonus: +5 Health from Potions',
2: 'Vitality: +20 Max Health.  Class Bonus: +5 Health from Potions',
3: 'Vitality: +20 Max Health.  Class Bonus: +5 Health from Potions',
4: 'Vitality: +20 Max Health.  Class Bonus: +5 Health from Potions',
5: 'Vitality: +20 Max Health.  Class Bonus: +5 Health from Potions',
6: 'Stockpile: +2 Max Grenades.  Class Bonus: +1 Grenade from Loot Piles',
7: 'Stockpile: +2 Max Grenades.  Class Bonus: +1 Grenade from Loot Piles',
8: 'Stockpile: +2 Max Grenades.  Class Bonus: +1 Grenade from Loot Piles',
9: 'Stockpile: +2 Max Grenades.  Class Bonus: +1 Grenade from Loot Piles',
10: 'Stockpile: +2 Max Grenades.  Class Bonus: +1 Grenade from Loot Piles',
11: 'Protection: +15 Max Shields.  Class Bonus: +10 Recharge Rate',
12: 'Protection: +15 Max Shields.  Class Bonus: +10 Recharge Rate',
13: 'Protection: +15 Max Shields.  Class Bonus: +10 Recharge Rate',
14: 'Protection: +15 Max Shields.  Class Bonus: +10 Recharge Rate',
15: 'Protection: +15 Max Shields.  Class Bonus: +10 Recharge Rate',
16: 'Aggression: +3 Damage for Favored Gun.  Class Bonus: +1 Damage to all Guns',
17: 'Aggression: +3 Damage for Favored Gun.  Class Bonus: +1 Damage to all Guns',
18: 'Aggression: +3 Damage for Favored Gun.  Class Bonus: +1 Damage to all Guns',
19: 'Aggression: +3 Damage for Favored Gun.  Class Bonus: +1 Damage to all Guns',
20: 'Aggression: +3 Damage for Favored Gun.  Class Bonus: +1 Damage to all Guns',
21: 'Resistance: +1d4 Elemental Resistance.  Class Bonus: +1d4 Damage Resistance',
22: 'Resistance: +1d4 Elemental Resistance.  Class Bonus: +1d4 Damage Resistance',
23: 'Resistance: +1d4 Elemental Resistance.  Class Bonus: +1d4 Damage Resistance',
24: 'Resistance: +1d4 Elemental Resistance.  Class Bonus: +1d4 Damage Resistance',
25: 'Resistance: +1d4 Elemental Resistance.  Class Bonus: +1d4 Damage Resistance',
26: 'Tenacity: +1 Initiative Mod.  Class Bonus: +10 Health.',
27: 'Tenacity: +1 Initiative Mod.  Class Bonus: +10 Health.',
28: 'Tenacity: +1 Initiative Mod.  Class Bonus: +10 Health.',
29: 'Tenacity: +1 Initiative Mod.  Class Bonus: +10 Health.',
30: 'Tenacity: +1 Initiative Mod.  Class Bonus: +10 Health.',
31: 'Elemental: +2 Elemental Damage.  Class Bonus: +20% on Elemental Rolls',
32: 'Elemental: +2 Elemental Damage.  Class Bonus: +20% on Elemental Rolls',
33: 'Elemental: +2 Elemental Damage.  Class Bonus: +20% on Elemental Rolls',
34: 'Elemental: +2 Elemental Damage.  Class Bonus: +20% on Elemental Rolls',
35: 'Elemental: +2 Elemental Damage.  Class Bonus: +20% on Elemental Rolls',
36: 'Strength: +3 Melee Damage.  Class Bonus: +1 Melee Attack/turn',
37: 'Strength: +3 Melee Damage.  Class Bonus: +1 Melee Attack/turn',
38: 'Strength: +3 Melee Damage.  Class Bonus: +1 Melee Attack/turn',
39: 'Strength: +3 Melee Damage.  Class Bonus: +1 Melee Attack/turn',
40: 'Strength: +3 Melee Damage.  Class Bonus: +1 Melee Attack/turn',
41: 'Vitality: +30 Max Health.  Class Bonus: +10 Health from Potions',
42: 'Vitality: +30 Max Health.  Class Bonus: +10 Health from Potions',
43: 'Vitality: +30 Max Health.  Class Bonus: +10 Health from Potions',
44: 'Vitality: +30 Max Health.  Class Bonus: +10 Health from Potions',
45: 'Vitality: +30 Max Health.  Class Bonus: +10 Health from Potions',
46: 'Stockpile: +2 Max Grenades.  Class Bonus: +2 Grenade from Loot Piles',
47: 'Stockpile: +2 Max Grenades.  Class Bonus: +2 Grenade from Loot Piles',
48: 'Stockpile: +2 Max Grenades.  Class Bonus: +2 Grenade from Loot Piles',
49: 'Stockpile: +2 Max Grenades.  Class Bonus: +2 Grenade from Loot Piles',
50: 'Stockpile: +2 Max Grenades.  Class Bonus: +2 Grenade from Loot Piles',
51: 'Protection: +20 Max Shields.  Class Bonus: +15 Recharge Rate',
52: 'Protection: +20 Max Shields.  Class Bonus: +15 Recharge Rate',
53: 'Protection: +20 Max Shields.  Class Bonus: +15 Recharge Rate',
54: 'Protection: +20 Max Shields.  Class Bonus: +15 Recharge Rate',
55: 'Protection: +20 Max Shields.  Class Bonus: +15 Recharge Rate',
56: 'Aggression: +4 Damage for Favored Gun.  Class Bonus: +2 Damage to all Guns',
57: 'Aggression: +4 Damage for Favored Gun.  Class Bonus: +2 Damage to all Guns',
58: 'Aggression: +4 Damage for Favored Gun.  Class Bonus: +2 Damage to all Guns',
59: 'Aggression: +4 Damage for Favored Gun.  Class Bonus: +2 Damage to all Guns',
60: 'Aggression: +4 Damage for Favored Gun.  Class Bonus: +2 Damage to all Guns',
61: 'Resistance: +1d6 Elemental Resistance.  Class Bonus: +1d6 Damage Resistance',
62: 'Resistance: +1d6 Elemental Resistance.  Class Bonus: +1d6 Damage Resistance',
63: 'Resistance: +1d6 Elemental Resistance.  Class Bonus: +1d6 Damage Resistance',
64: 'Resistance: +1d6 Elemental Resistance.  Class Bonus: +1d6 Damage Resistance',
65: 'Resistance: +1d6 Elemental Resistance.  Class Bonus: +1d6 Damage Resistance',
66: 'Tenacity: +2 Initiative Mod.  Class Bonus: +15 Health.',
67: 'Tenacity: +2 Initiative Mod.  Class Bonus: +15 Health.',
68: 'Tenacity: +2 Initiative Mod.  Class Bonus: +15 Health.',
69: 'Tenacity: +2 Initiative Mod.  Class Bonus: +15 Health.',
70: 'Tenacity: +2 Initiative Mod.  Class Bonus: +15 Health.',
71: 'Elemental: +3 Elemental Damage.  Class Bonus: +30% on Elemental Rolls',
72: 'Elemental: +3 Elemental Damage.  Class Bonus: +30% on Elemental Rolls',
73: 'Elemental: +3 Elemental Damage.  Class Bonus: +30% on Elemental Rolls',
74: 'Elemental: +3 Elemental Damage.  Class Bonus: +30% on Elemental Rolls',
75: 'Elemental: +3 Elemental Damage.  Class Bonus: +30% on Elemental Rolls',
76: 'Strength: +4 Melee Damage.  Class Bonus: +2 Melee Attack/turn',
77: 'Strength: +4 Melee Damage.  Class Bonus: +2 Melee Attack/turn',
78: 'Strength: +4 Melee Damage.  Class Bonus: +2 Melee Attack/turn',
79: 'Strength: +4 Melee Damage.  Class Bonus: +2 Melee Attack/turn',
80: 'Strength: +4 Melee Damage.  Class Bonus: +2 Melee Attack/turn',
81: 'Vitality: +40 Max Health.  Class Bonus: +15 Health from Potions',
82: 'Vitality: +40 Max Health.  Class Bonus: +15 Health from Potions',
83: 'Vitality: +40 Max Health.  Class Bonus: +15 Health from Potions',
84: 'Stockpile: +4 Max Grenades.  Class Bonus: +3 Grenade from Loot Piles',
85: 'Stockpile: +4 Max Grenades.  Class Bonus: +3 Grenade from Loot Piles',
86: 'Protection: +25 Max Shields.  Class Bonus: +20 Recharge Rate',
87: 'Protection: +25 Max Shields.  Class Bonus: +20 Recharge Rate',
88: 'Protection: +25 Max Shields.  Class Bonus: +20 Recharge Rate',
89: 'Aggression: +5 Damage for Favored Gun.  Class Bonus: +3 Damage to all Guns',
90: 'Aggression: +5 Damage for Favored Gun.  Class Bonus: +3 Damage to all Guns',
91: 'Aggression: +5 Damage for Favored Gun.  Class Bonus: +3 Damage to all Guns',
92: 'Resistance: +1d8 Elemental Resistance.  Class Bonus: +1d8 Damage Resistance',
93: 'Resistance: +1d8 Elemental Resistance.  Class Bonus: +1d8 Damage Resistance',
94: 'Resistance: +1d8 Elemental Resistance.  Class Bonus: +1d8 Damage Resistance',
95: 'Tenacity: +3 Initiative Mod.  Class Bonus: +20 Health.',
96: 'Tenacity: +3 Initiative Mod.  Class Bonus: +20 Health.',
97: 'Elemental: +4 Elemental Damage.  Class Bonus: +40% on Elemental Rolls',
98: 'Elemental: +4 Elemental Damage.  Class Bonus: +40% on Elemental Rolls',
99: 'Strength: +5 Melee Damage.  Class Bonus: +3 Melee Attack/turn',
100: 'Strength: +5 Melee Damage.  Class Bonus: +3 Melee Attack/turn'
}


def relic_gen():
    pc_class = class_relics[(random.randint(1,10))]
    relic = relics[(random.randint(1,100))]
    return pc_class + ' ' + relic

